// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zucfxuhwogjljwbvfwda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1Y2Z4dWh3b2dqbGp3YnZmd2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDY0NTgsImV4cCI6MjA3MzUyMjQ1OH0.8_daw3AXw1QrlyqzWJoU-WNncL5QOf6Yx-SbvITsmX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});